#ifndef LOOP_VARY_H
#define LOOP_VARY_H

#include <stdio.h> // For FILE*
#include <windows.h> // For HANDLE and WIN32_FIND_DATAA if needed by functions generated by loop_vary.c

// Function to write a polymorphic file processing loop
void write_file_loop(FILE *out, const char *var_find_handle, const char *var_find_data, 
                     const char *var_out_dir, const char *var_temp_buf, const char *var_loop_counter,
                     unsigned int seed, int ext_index);

#endif // LOOP_VARY_H